#!mast -x Syckfile -x PROFILE .ruby bin lib man spec test [A-Z]*
.ruby
bin/mast
lib/mast/cli.rb
lib/mast/core_ext.rb
lib/mast/manifest.rb
lib/mast.rb
lib/mast.yml
lib/plugins/syckle/mast.rb
man/man1/mast.1
HISTORY.rdoc
LICENSE
README.rdoc
VERSION
