.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MAST" "1" "November 2010" "" ""
.
.SH "NAME"
\fBmast\fR \- manifest generator
.
.SH "SYNOPSIS"
\fBmast [<command>] [<options>\.\.\.]\fR
.
.SH "DESCRIPTION"
The manifest listing tool is used to list, create or update a manifest for a directory (eg\. to define a "package"), or compare a manifest to actual directory contents\. Mast is part of the ProUtils set of tools\.
.
.P
When no command is given, a manifest is dumped to standard out\. If \-\-file is specified, it will generate to that file instead\.
.
.SH "COMMANDS"
.
.TP
\fB\-c\fR, \fB\-\-create\fR
Generate a new manifest\. (default)
.
.TP
\fB\-u\fR, \fB\-\-update\fR
Update an existing manifest\.
.
.TP
\fB\-l\fR, \fB\-\-list\fR
List the files given in the manifest file\. (Use \-f to specify an alternate file\.)
.
.TP
\fB\-D\fR, \fB\-\-diff\fR
Diff manifest file against actual\.
.
.TP
\fB\-n\fR, \fB\-\-new\fR
List existant files that are not given in the manifest\.
.
.TP
\fB\-o\fR, \fB\-\-old\fR
List files given in the manifest but are non\-existent\.
.
.TP
\fB\-v\fR, \fB\-\-verify\fR
Verify that a manifest matches actual\.
.
.TP
\fB\-\-clean\fR
Remove non\-manifest files\. (Will ask for confirmation first\.)
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help message\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR, \fB\-\-all\fR
Include all files\. This deactivates deafult exclusions so it is possible to make complete list of all contents\.
.
.TP
\fB\-d\fR, \fB\-\-dir\fR
When creating a list include directory paths; by default only files are listed\.
.
.TP
\fB\-b\fR, \fB\-\-bang\fR
Generate manifest using the options from the bang line of the manifest file\.
.
.TP
\fB\-f\fR, \fB\-\-file PATH\fR
Path to manifest file\. This applies to comparison commands\. If not given then the file matching \'MANIFEST\', case\-insensitive and with an optional \'\.txt\' extension, in the current directory is used\. If the path of the manifest file is anything else then the \-\-file option must be specified\.
.
.TP
\fB\-g\fR, \fB\-\-digest TYPE\fR
Include crytographic signiture\. Type can be either md5, sha1, sha128, sha256, or sha512\.
.
.TP
\fB\-x\fR, \fB\-\-exclude PATH\fR
Exclude a file or dir from the manifest matching against full pathname\. You can use \-\-exclude repeatedly\.
.
.TP
\fB\-i\fR, \fB\-\-ignore PATH\fR
Exclude a file or dir from the manifest matching against an entries basename\. You can use \-\-ignore repeatedly\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress any extraneous output\.
.
.SH "EXAMPLES"
\fBmast\fR
.
.br
\fBmast \-u \-f PUBLISH\fR
.
.SH "SEE ALSO"
ls(1)
